name: Testing Workflow

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java 15
        uses: joschi/setup-jdk@v2
        with:
          java-version: '8'

      - name: Run Kotlin Linter
        run: ./gradlew ktlintStagingDebugCheck

      - name: Run Android Linter
        run: ./gradlew lintStagingDebug

      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew assembleStagingDebug

      - name: Assemble Debug Test APK
        run: ./gradlew assembleStagingDebugAndroidTest
