
name: Deploy Workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java 8
        uses: joschi/setup-jdk@v2
        with:
          java-version: '8'

      # Step 3: Decode the service account json key, needed on the next job
      - name: Decode service account key
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: echo $SERVICE_ACCOUNT > app/service-account-key.json

#      # Step 4: Publish the APK to the Play Store using the release keystore
#      - name: Publish APK
#        env:
#          RELEASE_KEYSTORE_PASSWORD: ${{ secrests.RELEASE_KEYSTORE_PASSWORD }}
#          RELEASE_KEY_ALIAS: ${{ secrests.RELEASE_KEY_ALIAS }}
#          RELEASE_KEY_PASSWORD: ${{ secrests.RELEASE_KEY_PASSWORD }}
#        run: ./gradlew publishStagingRelease
