name: Testing Workflow

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java 8
        uses: joschi/setup-jdk@v2
        with:
          java-version: '8'

      - name: Run Linter
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: Assemble Debug Test APK
        run: ./gradlew assembleDebugAndroidTest
