name: CI Workflow

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 8
        uses: joschi/setup-jdk@v2
        with:
          java-version: '8'

      - name: Run Linter
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Assemble Debug Bundle
        run: ./gradlew bundleDebug
